/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFamv1 = 'MyFlutterAppv1';
  static const String? _kFontPkg = null;

  static const IconData twitter =
      IconData(0xf099, fontFamily: _kFontFamv1, fontPackage: _kFontPkg);
  static const IconData instagram =
      IconData(0xf16d, fontFamily: _kFontFamv1, fontPackage: _kFontPkg);
  static const IconData whatsapp =
      IconData(0xf232, fontFamily: _kFontFamv1, fontPackage: _kFontPkg);
  static const IconData snapchat_ghost =
      IconData(0xf2ac, fontFamily: _kFontFamv1, fontPackage: _kFontPkg);
  static const IconData facebook_squared =
      IconData(0xf308, fontFamily: _kFontFamv1, fontPackage: _kFontPkg);
  static const IconData linkedin_squared =
      IconData(0xf30c, fontFamily: _kFontFamv1, fontPackage: _kFontPkg);
  ////////////////////////////////////////
  static const _kFontFamv2 = 'MyFlutterAppv2';
  static const IconData tags =
      IconData(0xe800, fontFamily: _kFontFamv2, fontPackage: _kFontPkg);
  static const IconData thumbs_up =
      IconData(0xe801, fontFamily: _kFontFamv2, fontPackage: _kFontPkg);
  static const IconData th_list =
      IconData(0xe802, fontFamily: _kFontFamv2, fontPackage: _kFontPkg);
  static const IconData star =
      IconData(0xe803, fontFamily: _kFontFamv2, fontPackage: _kFontPkg);
  static const IconData fire =
      IconData(0xf06d, fontFamily: _kFontFamv2, fontPackage: _kFontPkg);
  static const IconData mail_alt =
      IconData(0xf0e0, fontFamily: _kFontFamv2, fontPackage: _kFontPkg);
  static const IconData paper_plane =
      IconData(0xf1d8, fontFamily: _kFontFamv2, fontPackage: _kFontPkg);
  static const IconData fire_alt =
      IconData(0xf7e4, fontFamily: _kFontFamv2, fontPackage: _kFontPkg);
}
